version: '3.1'
services:
  ipfsjs-s3:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    working_dir: /usr/app
    ports:
      - 4002:4002
      - 4003:4003
      - 5002:5002
      - 9090:9090
    volumes:
      - .:/usr/app
    command: npm run dev:docker
